export const KERALA_PLACES_SOURCE = {
  title: "LIST OF VILLAGES WITH ONLINE TR AS on 15/7/19",
  fileName: 'TalukWiseListDigitisedVillagesKerala.xls',
  sourceType: 'Kerala Revenue and Land Reforms Department / OGD download supplied locally',
  sourceDate: '2019-07-15',
  rows: 1644,
} as const;

export const KERALA_VILLAGES: Record<string, Record<string, string[]>> = {
  "Thiruvananthapuram": {
    "Chirayinkeezh": [
      "Alamcode",
      "Anchuthengu",
      "Attingal",
      "Avanavancherry",
      "Azhoor",
      "Edakode",
      "Elamba",
      "Kadakkavur",
      "Karavaram",
      "Keezhattingal",
      "Kilimanoor",
      "Kizhuvillam",
      "Koduvazhanoor",
      "Koonthalloor",
      "Mudhakkal",
      "Nagaroor",
      "Pazhayakunnummel",
      "Pulimath",
      "Sarkara",
      "Vakkam",
      "Vellalloor"
    ],
    "Kattakada": [
      "Amboori",
      "Kallikkad",
      "Keezharoor",
      "Kulathummal",
      "Malayinkeezh",
      "Mannoorkkara",
      "Maranallur",
      "Ottasekharamangalam",
      "Perumkulam",
      "Vazhichal",
      "Veeranakav",
      "Vilappil",
      "Vilavoorkal"
    ],
    "Nedumangad": [
      "Anad",
      "Aruvikkara",
      "Aryanad",
      "Kallara Nedumangad",
      "Karakulam",
      "Karippur",
      "Koliyacode",
      "Kurupuzha",
      "Manikkal",
      "Nedumangad",
      "Nellanad",
      "Palode",
      "Panavoor",
      "Pangode",
      "Peringammala",
      "Pullampara",
      "Thekkada",
      "Thennoor",
      "Tholicode",
      "Uzhamalakkal",
      "Vamanapuram",
      "Vattappara",
      "Vellanad",
      "Vembayam",
      "Vithura"
    ],
    "Neyyattinkara": [
      "Anavoor",
      "Athiyannoor",
      "Balaramapuram",
      "Chenkal",
      "Kanjiramkulam",
      "Karode",
      "Karumkulam",
      "Kollayil",
      "Kottukal",
      "Kulathoor",
      "Kunnathukal",
      "Neyyattinkara",
      "Pallichal",
      "Parassala",
      "Parasuvaikkal",
      "Perumkadavila",
      "Perumpazhuthoor",
      "Poovar",
      "Thirupuram",
      "Vellarada",
      "Vizhinjam"
    ],
    "Thiruvananthapuram": [
      "Andoorkonam",
      "Attipra",
      "Ayiroopara",
      "Cheruvakkal",
      "Kadakampally",
      "Kadinamkulam",
      "Kalliyoor",
      "Kazhakoottam",
      "Keezhthonnakkal",
      "Kowdiar",
      "Kudappanakunnu",
      "Manacaud",
      "Melthonackal",
      "Menamkulam",
      "Muttathara",
      "Nemom",
      "Pallipuram Trivandrum",
      "Pangapara",
      "Pattom",
      "Peroorkada",
      "Pettah",
      "Sasthamangalam",
      "Thirumala",
      "Thiruvallam",
      "Thycaud",
      "Uliyazhathura",
      "Uloor",
      "Vanchiyoor",
      "Vattiyoorkavu",
      "Veganoor",
      "Veiloor"
    ],
    "Varkala": [
      "Ayiroor",
      "Chemmaruthi",
      "Cherunniyur",
      "Edava",
      "Kudavoor",
      "Madavoor",
      "Manamboor",
      "Navaikulam",
      "Ottur",
      "Pallikkal",
      "Varkala",
      "Vettur"
    ]
  },
  "Kollam": {
    "Karunagappally": [
      "Adinad",
      "Alappad Kollam",
      "Ayanivelikulangara",
      "Chavara",
      "Clappana",
      "Kallalibhagom",
      "Karunagappally",
      "Kulasekharapuram",
      "Neendakara",
      "Ochira",
      "Panmana",
      "Pavumba",
      "Thazhava",
      "Thekkumbhagom Karunagapally",
      "Thevalakkara",
      "Thodiyoor",
      "Vadakumthala"
    ],
    "Kollam": [
      "Adichanallur",
      "Chirakkara",
      "East Kallada",
      "Elampallur",
      "Eravipuram",
      "Kalluvathukkal",
      "Kilikollur",
      "Kollam East",
      "Kollam West",
      "Kottamkara",
      "Kottappuram",
      "Mandrothuruth",
      "Mangadu Kollam",
      "Mayyanad",
      "Meenad",
      "Mulavana",
      "Mundakkal",
      "Nedumpana",
      "Pallimon",
      "Panayam",
      "Paravoor",
      "Parippally",
      "Perayam",
      "Perinad Kollam",
      "Poothakulam",
      "Shakthikulangara",
      "Thazhuthala",
      "Thrikkadavoor",
      "Thrikkaruva",
      "Thrikkovilvattom",
      "Vadakkevila"
    ],
    "Kottarakkara": [
      "Chadayamangalam",
      "Chakkuvarakkal",
      "Chithara",
      "Elamad",
      "Ezhukone",
      "Ittiva",
      "Kadakkal",
      "Kalayapuram",
      "Kareepra",
      "Kottarakkara",
      "Kottukkal",
      "Kulakkada",
      "Kummil",
      "Mankode",
      "Melila",
      "Mylom",
      "Neduvathur",
      "Nilamel",
      "Odanavattom",
      "Pavithreswaram",
      "Pooyappally",
      "Puthur Kollam",
      "Ummannur",
      "Valakom",
      "Velinallur",
      "Veliyam",
      "Vettikkavala"
    ],
    "Kunnathur": [
      "Kunnathur",
      "Mynagappally",
      "Poruvazhi",
      "Sasthamkotta",
      "Sooranad North",
      "Sooranad South",
      "West Kallada"
    ],
    "Pathanapuram": [
      "Pathanapuram",
      "Pattazhy",
      "Pattazhy Vadakkekkara",
      "Pidavoor",
      "Piravanthoor",
      "Punnala",
      "Thalavoor",
      "Vilakudy"
    ],
    "Punalur": [
      "Alayaman",
      "Anchal",
      "Arakkal",
      "Ariyankavu",
      "Ayiranelloor",
      "Channapetta",
      "Edamon",
      "Edamulakkal",
      "Eroor",
      "Karavaloor",
      "Kulathupuzha",
      "Punalur",
      "Thenmala",
      "Thinkalkarikkom",
      "Valakkode"
    ]
  },
  "Pathanamthitta": {
    "Adoor": [
      "Adoor",
      "Angadickal",
      "Enadimangalam",
      "Enathu",
      "Erathu",
      "Ezhamkulam",
      "Kadambanad",
      "Kodumon",
      "Kurampala",
      "Pallickal",
      "Pandalam",
      "Pandalam-thekkekara",
      "Peringnad",
      "Thumpamon"
    ],
    "Konni": [
      "Aruvappalum",
      "Chittar",
      "Iravon",
      "Kalanjoor",
      "Konni",
      "Konnithazham",
      "Koodal",
      "Malayalapuzha",
      "Mylapra",
      "Pramadom",
      "Seethathode",
      "Thannithode",
      "Vallicodu",
      "Vallicodu Kottayam"
    ],
    "Kozhenchery": [
      "Aranmula",
      "Chenneerkara",
      "Elanthoor",
      "Kidangannur",
      "Kozhenchery",
      "Kulanada",
      "Mallapuzhasserry",
      "Mezhuveli",
      "Naranganam",
      "Omallur",
      "Pathanamthitta"
    ],
    "Mallappally": [
      "Anicadu",
      "Ezhumattoor",
      "Kalloorppara",
      "Kottangal",
      "Kunnamthanam",
      "Mallapally",
      "Perumpetty",
      "Puramattom",
      "Thelliyoor"
    ],
    "Ranni": [
      "Angadi",
      "Athikayam",
      "Ayroor",
      "Cherukole",
      "Chetakkal",
      "Kollamula",
      "Pazhavangadi Ranni",
      "Perunadu Ranni",
      "Ranny",
      "Vadasserikara"
    ],
    "Thiruvalla": [
      "Eraviperoor",
      "Kadapra",
      "Kaviyoor",
      "Kavumbhagom",
      "Koipuram",
      "Kuttapuzha",
      "Kuttoor Thiruvalla",
      "Nedumpram",
      "Niranam",
      "Peringra",
      "Thiruvalla",
      "Thottapuzhasserry"
    ]
  },
  "Alappuzha": {
    "Ambalappuzha": [
      "Alappuzha West",
      "Ambalappuzha",
      "Ambalappuzha North",
      "Aryad South",
      "Kalavoor",
      "Karumady",
      "Komalapuram",
      "Mannancherry",
      "Mullackal",
      "Paravur Alapuzha",
      "Pathirappally",
      "Pazhaveedu",
      "Punnapra",
      "Purakkad"
    ],
    "Chengannur": [
      "Aala Chengannur",
      "Chengannur",
      "Cheriyanad",
      "Ennakkad",
      "Kurattissery",
      "Mannar",
      "Mulakkuzha",
      "Pandanad",
      "Puliyur",
      "Thiruvanvandoor",
      "Venmony"
    ],
    "Cherthala": [
      "Arookkutty",
      "Aroor",
      "Arthunkal",
      "Cherthala North",
      "Cherthala South",
      "Ezhupunna",
      "Kadakkarappally",
      "Kanjikkuzhi",
      "Kodamthuruthu",
      "Kuthiathodu",
      "Mararikulam North",
      "Pallypuram Cherthala",
      "Panavally",
      "Pattanakkad",
      "Perumbalam",
      "Thanneermkkom South",
      "Thanneermukkom North",
      "Thuravoor South",
      "Thykkattussery",
      "Vayalar East"
    ],
    "Karthikappally": [
      "Arattupuzha",
      "Cheppad",
      "Cheruthana",
      "Chingoli",
      "Harippad",
      "Kandalloor",
      "Karthikappally",
      "Karuvatta",
      "Kayamkulam",
      "Keerikkad",
      "Krishnapuram",
      "Kumarapuram",
      "Muthukulam",
      "Pallippad",
      "Pathiyur",
      "Puthupalli Karthikapally",
      "Thrikkunnappuzha",
      "Veeyapuram"
    ],
    "Kuttanad": [
      "Champakkulam",
      "Edathuva",
      "Kainakary North",
      "Kainakary South",
      "Kavalam",
      "Kunnumma",
      "Muttar",
      "Nedumudy",
      "Neelamperur",
      "Pulimkunnu",
      "Ramankary",
      "Thakazhy",
      "Thalavady",
      "Veliyanadu"
    ],
    "Mavelikkara": [
      "Bharanikkavu",
      "Chennithala",
      "Chunakkara",
      "Kannamangalam",
      "Kattanam",
      "Mavelikkara",
      "Nooranad",
      "Palamel",
      "Peringala",
      "Thamarakkulam",
      "Thazhakkara",
      "Thekkekkara",
      "Thripperumthura",
      "Vallikunnam",
      "Vettiyar"
    ]
  },
  "Kottayam": {
    "Changanassery": [
      "Changannassery",
      "Chethippuzha",
      "Kangazha",
      "Karukachal",
      "Kurichy",
      "Madappally",
      "Nedumkunnam",
      "Payippadu",
      "Thottakkadu",
      "Thrikkodithanam",
      "Vakathanam",
      "Vazhappally Kizhakku",
      "Vazhappally Padinjaru",
      "Vazhoor",
      "Vellavoor"
    ],
    "Kanjirappally": [
      "Cheruvally",
      "Chirakkadavu",
      "Edakkunnam",
      "Elangulam",
      "Elikkulam",
      "Erumeli North",
      "Erumeli South",
      "Kanjirappally",
      "Koottickal",
      "Koovappally",
      "Koruthodu",
      "Manimala",
      "Mundakkayam"
    ],
    "Kottayam": [
      "Akalakkunnam",
      "Anikkadu",
      "Arppookkara",
      "Athirampuzha",
      "Ayarkkunnam",
      "Aymanam",
      "Chengalam East",
      "Chengalam South",
      "Ettumanoor",
      "Kaippuzha",
      "Kooroppada",
      "Kottayam",
      "Kumarakom",
      "Manarcadu",
      "Meenadom",
      "Muttambalam",
      "Nattakom",
      "Onamthuruth",
      "Pampady Kottayam",
      "Panachikkadu",
      "Peroor",
      "Perumbayikkadu",
      "Puthuppally Kottayam",
      "Thiruvarppu",
      "Veloor",
      "Vijayapuram"
    ],
    "Meenachil": [
      "Bharananganam",
      "Elackadu",
      "Erattupetta",
      "Kadanadu",
      "Kadaplamattom",
      "Kanakkari",
      "Kidangoor",
      "Kondur",
      "Kuravilangadu",
      "Kurichithanam",
      "Lalam",
      "Meenachil",
      "Melukavu",
      "Monippally",
      "Moonnilavu",
      "Poonjar",
      "Poonjar Nadubhagam",
      "Poonjar Thekkekkara",
      "Poovarani",
      "Puliyannoor",
      "Ramapuram",
      "Thalanadu",
      "Thalappalam",
      "Theekoy",
      "Uzhavoor",
      "Vallichira",
      "Veliyannoor",
      "Vellilappally"
    ],
    "Vaikom": [
      "Chempu",
      "Kaduthurithy",
      "Kallara Vaikom",
      "Kothanalloor",
      "Kulashekaramangalam",
      "Manjoor",
      "Mulakkulam",
      "Muttuchira",
      "Naduvila",
      "Njeezhoor",
      "T V Puram",
      "Thalayazham",
      "Udayanapuram",
      "Vadakkemuri",
      "Vadayar",
      "Vaikom",
      "Vechoor",
      "Velloor"
    ]
  },
  "Idukki": {
    "Devikulam": [
      "Anaviratty",
      "Kanthalloor",
      "Keezhanthoor",
      "Kunjithanny",
      "Mankulam",
      "Mannamkandam",
      "Marayoor",
      "Pallivasal",
      "Vellathooval"
    ],
    "Idukki": [
      "Ayyappancoil",
      "Idukki",
      "Kanjikuzhy",
      "Kattappana",
      "Konnathady",
      "Thankamony",
      "Upputhode",
      "Vathikudy"
    ],
    "Peerumade": [
      "Elappara",
      "Kokkayar",
      "Kumily",
      "Manchumala",
      "Mlappara",
      "Peermade",
      "Periyar",
      "Peruvanthanam",
      "Upputhara"
    ],
    "Thodupuzha": [
      "Alakkode",
      "Arakkulam",
      "Elappally",
      "Karikkode",
      "Karimannoor",
      "Karimkunnam",
      "Kodikkulam",
      "Kudayathoor",
      "Kumaramangalam",
      "Manakkad",
      "Muttom",
      "Neyyasserry",
      "Purappuzha",
      "Thodupuzha",
      "Udumbannoor",
      "Vannappuram",
      "Velliyamattam"
    ],
    "Udumbanchola": [
      "Anakara Udumbanchola",
      "Anavilasom",
      "Bysonvalley",
      "Chakkupallam",
      "Erattayar",
      "Kalkoonthal",
      "Kanthippara",
      "Karunapuram",
      "Pampadumpara",
      "Parathode",
      "Pooppara",
      "Rajakkad",
      "Rajakumary",
      "Santhanpara",
      "Udumbanchola",
      "Vandenmedu"
    ]
  },
  "Ernakulam": {
    "Aluva": [
      "Aluva East",
      "Aluva West",
      "Angamaly",
      "Ayyampuzha",
      "Chengamanad",
      "Choornikkara",
      "Chowara",
      "Kalady",
      "Karukutty",
      "Keezhmad",
      "Kizhakkumbhagom",
      "Malayattoor",
      "Manjapra",
      "Mattoor",
      "Mookkannoor",
      "Nedumbassery",
      "Parakkadavu",
      "Thekkumbhagam Aluva",
      "Thuravoor",
      "Vadakkumbhagom"
    ],
    "Kanayannor": [
      "Amballur Kanayannur",
      "Cheranallur",
      "Edakkattuvayal",
      "Edappally North",
      "Edappally South",
      "Elamkulam",
      "Ernakulam",
      "Kadamakkudy",
      "Kaippattur",
      "Kakkanad",
      "Kanayannur",
      "Keecherry",
      "Kulayettikara",
      "Kumbalam",
      "Kureekkad",
      "Manakunnam",
      "Maradu",
      "Mulamthuruthy",
      "Mulavukad",
      "Nadama",
      "Poonithura",
      "Thekkumbhagom Kanayannur",
      "Thiruvankulam",
      "Thrikkakara North",
      "Vazhakkala"
    ],
    "Kochi": [
      "Chellanam",
      "Edakochi",
      "Edavanakkad",
      "Elamkunnapuzha",
      "Fort Kochi",
      "Kumbalangy",
      "Kuzhuppilly",
      "Mattancherry",
      "Nayarambalam",
      "Njarackal",
      "Pallippuram Kochi",
      "Palluruthy",
      "Puthuvype",
      "Rameshwaram",
      "Thoppumpady"
    ],
    "Kothamangalam": [
      "Eramalloor",
      "Kedavoor Kothamangalam",
      "Keerampara",
      "Kothamangalam",
      "Kottappady",
      "Kuttamangalam",
      "Kuttampuzha",
      "Neriamangalam",
      "Pallarimangalam",
      "Pindimana",
      "Pothanikkad",
      "Thrikkariyoor",
      "Varappetty"
    ],
    "Kunnathunad": [
      "Aikaranad North",
      "Aikaranad South",
      "Arakapady",
      "Asamannoor",
      "Chelamattom",
      "Irapuram",
      "Kizhakkambalam",
      "Kodanad",
      "Kombanad",
      "Koovappady",
      "Kunnathunad",
      "Marampilly",
      "Mazhuvannoor",
      "Pattimattom",
      "Perumbavoor",
      "Puthencruz",
      "Rayamangalam",
      "Thiruvaniyoor",
      "Vadavukode",
      "Vazhakulam",
      "Vengola",
      "Vengoor",
      "Vengoor West"
    ],
    "Moovattupuzha": [
      "Arakuzha",
      "Elanji",
      "Enanalloor",
      "Kalloorkkad",
      "Koothattukulam",
      "Maneed",
      "Manjalloor",
      "Marady",
      "Memmury",
      "Mulavoor",
      "Muvattupuzha",
      "Onakkoor",
      "Palakuzha",
      "Piravom",
      "Ramamangalam",
      "Thirumarady",
      "Valakam",
      "Velloorkunnam"
    ],
    "Paravur": [
      "Alangad",
      "Chendamangalam",
      "Eloor",
      "Ezhikkara",
      "Kadungalloor",
      "Karumalloor",
      "Kottuvally",
      "Kunnukara",
      "Moothakunnam",
      "Paravur",
      "Puthenvelikkara",
      "Vadakkekara",
      "Varappuzha"
    ]
  },
  "Thrissur": {
    "Chalakkudy": [
      "Alathur Tcr",
      "Aloor Chalakudy",
      "Annallur",
      "Athirapilly",
      "Elinjipra",
      "Kadukutty",
      "Kakkulissery",
      "Kallettumkara",
      "Kallur Thekkummuri",
      "Kizhakke Chalakudi",
      "Kizhakkumury Chalakudy",
      "Kodakara",
      "Kodassery",
      "Kuruvilassery",
      "Kuttichira",
      "Mattathur",
      "Melur",
      "Muppiliyam",
      "Muringoor Thekkummuri",
      "Muringoor Vadakkummuri",
      "Nandipulam",
      "Padinjare Chalakudi",
      "Pariyaram",
      "Perambra Chalakudy",
      "Potta",
      "Thazhekkad",
      "Thirumukkulam",
      "Vadakkumbhagam",
      "Vadama",
      "Varandarapilly",
      "Vellikulangara"
    ],
    "Chavakkad": [
      "Annakara",
      "Brahmakulam",
      "Chavakkad",
      "Edakkazhiyur",
      "Elavally",
      "Engandiyur",
      "Guruvayur",
      "Irimbranellur",
      "Iringapram",
      "Kadappuram",
      "Kadikkad",
      "Kundaliyur",
      "Manathala",
      "Mullassery",
      "Nattika",
      "Orumanayoor",
      "Pavaratty",
      "Perakam",
      "Pookode",
      "Punnayur",
      "Punnayurkulam",
      "Thaikkad Chavakkad",
      "Thalikkulam",
      "Vadakkekad",
      "Vadanappilly",
      "Valappad",
      "Venkidangu",
      "Venmanad",
      "Vylathur"
    ],
    "Kodungallur": [
      "Ala Kodungallur",
      "Azhikode",
      "Chendrapinni",
      "Edathiruthy",
      "Edavilangu",
      "Eriyad",
      "Kaipamangalam",
      "Koolimuttom",
      "Lokamaleswaram",
      "Madathumpady",
      "Methala",
      "Padinjare Vemballur",
      "Pallipuram Kodungallur",
      "Panagad",
      "Pappinivattom",
      "Perinjanam",
      "Poyya",
      "Pullutt"
    ],
    "Kunnamkulam": [
      "Akathiyoor",
      "Aloor Kunnamkulam",
      "Anjur Kunnamkulam",
      "Arthat",
      "Chemmanthitta",
      "Chiramanangad",
      "Chiranellur",
      "Choondal",
      "Chowannur",
      "Eranellur",
      "Eyyal",
      "Kadangode",
      "Kadavallur",
      "Kandanissery",
      "Kanipayyoor",
      "Karikkad",
      "Kariyannur",
      "Kattakampal",
      "Kiralur",
      "Kunnamkulam",
      "Mangad Kunnamkulam",
      "Nelluvai",
      "Pazhanji",
      "Perumpilavu",
      "Porkulam",
      "Thayyur",
      "Vellarakkad",
      "Vellattanjur",
      "Velur"
    ],
    "Mukundapuram": [
      "Amballoor Mukundapuram",
      "Anandapuram",
      "Chengalur",
      "Edathirinji",
      "Irinjalakuda",
      "Kaaralam",
      "Kaarumathra",
      "Kaduppassery",
      "Kallur",
      "Kattur",
      "Kottanellur",
      "Madayikkonam",
      "Manavalassery",
      "Muriyad",
      "Nellai",
      "Nenmanikkara",
      "Padiyoor Mukundapuram",
      "Parappukara",
      "Poomangalam",
      "Porathisseri",
      "Pulloor Mukundapuram",
      "Puthenchira",
      "Thekkumkkara",
      "Thoravu",
      "Thottippal",
      "Trikkur",
      "Vadakkumkara",
      "Vallivattom",
      "Velookkara"
    ],
    "Thalappilly": [
      "Arangottukara",
      "Attur",
      "Chelakkara",
      "Chelakkode",
      "Cheruthuruthy",
      "Chittanda",
      "Desamangalam",
      "Elanad",
      "Enkakkad",
      "Kaniyarkode",
      "Kanjirakkode",
      "Karumathra",
      "Killimangalam",
      "Kondaazhy",
      "Kottapuram",
      "Kumaranellur",
      "Kurumala",
      "Maayannur",
      "Manalithara",
      "Minalur",
      "Mullurkara",
      "Mundathikode",
      "Nedumpura",
      "Paimkulam",
      "Pallur",
      "Pambady Thalappilly",
      "Pangarappilly",
      "Panjal",
      "Parlikad",
      "Pazhayanur",
      "Peringandoor",
      "Pilakkode",
      "Pulakode",
      "Puthuruthy",
      "Thalassery Kannur",
      "Thekkumkara",
      "Thichur",
      "Thiruvilwamala",
      "Thonnurkara",
      "Vadakkethara",
      "Varavoor",
      "Venganellur",
      "Vennur",
      "Viruppakka",
      "Wadakkanchery"
    ],
    "Thrissur": [
      "Aalappatt Thrissur",
      "Adat",
      "Anjoor Thrissur",
      "Anthicad",
      "Aranattukara",
      "Aratupuzha",
      "Avanissery",
      "Avannur",
      "Ayyanthole",
      "Chalakkal",
      "Chazhoor",
      "Chembukavu",
      "Cherpu",
      "Chevvur",
      "Chittilappilly",
      "Chiyyaram",
      "Chulissery",
      "Edakkalathur",
      "Edakkunni",
      "Eravu",
      "Inchamudi",
      "Kainoor",
      "Kaiparambu",
      "Kanimangalam",
      "Karamukk",
      "Killannur",
      "Kizhakkummuri Thrissur",
      "Kizhuppillikkara",
      "Kodannur",
      "Kolazhy",
      "Koorkkanchery",
      "Kozhukully",
      "Kurichikkara",
      "Kurunpilavu",
      "Kuttoor Thrissur",
      "Madakkathara",
      "Manakkodi",
      "Manalur",
      "Mannamangalam",
      "Marathakkara",
      "Mulayam",
      "Nadathara",
      "Nettissery",
      "Ollukkara",
      "Ollur",
      "Oorakam",
      "Padiyam",
      "Palissery",
      "Pallipuram Tcr",
      "Pananchery",
      "Parakkad",
      "Paralam",
      "Peechi",
      "Peramangalam",
      "Pottore",
      "Pullazhi",
      "Pullu",
      "Puranattukara",
      "Puthur",
      "Puzhakkal",
      "Thangaloor",
      "Thanniyam",
      "Tholur",
      "Thrissur",
      "Vadakkummuri",
      "Vallachira",
      "Velappaya",
      "Vellanikkara",
      "Veluthur",
      "Venginissery",
      "Vilvattom",
      "Viyyur"
    ]
  },
  "Palakkad": {
    "Alathur": [
      "Alathur",
      "Erimayur I",
      "Erimayur Ii",
      "Kannambra I",
      "Kannambra Ii",
      "Kavassery I",
      "Kavassery Ii",
      "Kizhakkancherry I",
      "Kizhakkancherry Ii",
      "Kottayi I",
      "Kottayi Ii",
      "Kuthannur-i",
      "Kuthanoor-ii",
      "Kuzhalmandham I",
      "Kuzhalmandham Ii",
      "Mangalamdam",
      "Mathur I",
      "Mathur Ii",
      "Melarcode",
      "Peringottukurussy-i",
      "Peringottukurussy-ii",
      "Puducode",
      "Tarur I",
      "Tarur Ii",
      "Thenkurussy I",
      "Thenkurussy Ii",
      "Vadakkancherry I",
      "Vadakkancherry Ii",
      "Vandazhi I",
      "Vandazhi Ii"
    ],
    "Chittur": [
      "Ayilur",
      "Chittur",
      "Elavanchery",
      "Eruthempathy",
      "Kairady",
      "Koduvayur-i",
      "Koduvayur-ii",
      "Kollengode-i",
      "Kollengode-ii",
      "Kozhinjampara",
      "Kozhipathy",
      "Moolathara",
      "Muthalamada-i",
      "Muthalamada-ii",
      "Nalleppilly",
      "Nelliyampathy",
      "Nenmara",
      "Ozhalapathy",
      "Pallasaana",
      "Pattanchery",
      "Perumatty",
      "Pudunagaram",
      "Thattamangalam",
      "Thekkedesam",
      "Thiruvazhiyode",
      "Vadakarappathi",
      "Vadavannur",
      "Valiyavallampathy",
      "Vallanghi",
      "Vandithavalam"
    ],
    "Mannarkad": [
      "Agali",
      "Alanallur-i",
      "Alanallur-ii",
      "Alanallur-iii",
      "Kallamala",
      "Karakurussi",
      "Karimba1",
      "Karimba2",
      "Kotathara",
      "Kottoppadam-i",
      "Kottoppadam-ii",
      "Kottoppadam-iii",
      "Kumaramputhur",
      "Mannarkkad I",
      "Mannarkkad Ii",
      "Padavayal",
      "Palakkayam",
      "Payyanedam",
      "Pottasseri-i",
      "Pottasseri-ii",
      "Pudur",
      "Sholayur",
      "Thachampara",
      "Thachanattukara-i",
      "Thachanattukara-ii"
    ],
    "Ottappalam": [
      "Ambalappara I",
      "Ambalappara Ii",
      "Ananganadi",
      "Chalavara",
      "Cherpulacherry",
      "Kadampazhippuram I",
      "Kadampazhippuram Ii",
      "Karimpuzha I",
      "Karimpuzha Ii",
      "Lakkidiperur I",
      "Lakkidiperur Ii",
      "Nellaya",
      "Ottapalam I",
      "Ottapalam Ii",
      "Pookkottukavu",
      "Shoranur I",
      "Shoranur Ii",
      "Sreekrishnapuram I",
      "Sreekrishnapuram Ii",
      "Thrikkadeeri I",
      "Thrikkadeeri Ii",
      "Vaniyakulam I",
      "Vaniyakulam Ii",
      "Vellinezhi"
    ],
    "Palakkad": [
      "Akathethara",
      "Elappully I",
      "Elappuly Ii",
      "Kannadi I",
      "Kannadi Ii",
      "Keralassery",
      "Kodumba",
      "Kongad I",
      "Kongad Ii",
      "Malampuzha I",
      "Malampuzha Ii",
      "Mankara",
      "Mannur",
      "Maruthuroad",
      "Mundur I",
      "Mundur Ii",
      "Palakkad I",
      "Palakkad-2",
      "Palakkad-3",
      "Parali I",
      "Parali Ii",
      "Peruvembu",
      "Piriyari",
      "Polpully",
      "Puthuppariyaram I",
      "Puthuppariyaram Ii",
      "Puthusserry Central",
      "Puthusserry East",
      "Puthussery West",
      "Yakkara"
    ],
    "Pattambi": [
      "Aanakkara",
      "Chalissery",
      "Kappur",
      "Koppam",
      "Kulukkallur",
      "Muthuthala",
      "Nagalasserry",
      "Ongallur-i",
      "Ongallur-ii",
      "Paruthur",
      "Pattambi",
      "Pattithara",
      "Thirumittakkode-i",
      "Thirumittakode-ii",
      "Thiruvegappura",
      "Thrithala",
      "Vallapuzha",
      "Vilayur"
    ]
  },
  "Malappuram": {
    "Ernad": [
      "Anakkayam",
      "Areacode",
      "Chembrassery",
      "Edavanna",
      "Elankur",
      "Karakunnu",
      "Kavanur",
      "Keezhuparamba",
      "Malappuram",
      "Manjeri",
      "Melmuri",
      "Narukara",
      "Panakkad",
      "Pandallur",
      "Pandikkad",
      "Payyanad",
      "Perakamanna",
      "Pookkottur",
      "Pulpatta",
      "Thrikkalangode",
      "Urangattiri",
      "Vettikkattiri",
      "Vettilippara"
    ],
    "Kondotty": [
      "Cheekode",
      "Chelembra",
      "Cherukavu",
      "Kondotty",
      "Kuzhmanna",
      "Morayur",
      "Muthuvallur",
      "Nediyiruppu",
      "Pallikal",
      "Pulikkal",
      "Vazhakkad",
      "Vazhayur"
    ],
    "Nilambur": [
      "Akampadam",
      "Amarambalam",
      "Chokkad",
      "Chungathara",
      "Edakkara",
      "Kalikavu",
      "Karulai",
      "Karuvarakundu",
      "Kerala Estate",
      "Kurumbalangode",
      "Mampad",
      "Moothedam",
      "Nilambur",
      "Porur",
      "Pothukallu",
      "Pullippadam",
      "Thiruvali",
      "Thuvvur",
      "Vazhikkadavu",
      "Vellayur",
      "Wandoor"
    ],
    "Perinthalmanna": [
      "Aliparamba",
      "Anamangad",
      "Angadippuram",
      "Arakkuparamba",
      "Edapatta",
      "Elamkulam Malappuram",
      "Karyavattom",
      "Keezhattur",
      "Kodur",
      "Koottilangadi",
      "Kuruva",
      "Kuruvambalam",
      "Mankada",
      "Melattur",
      "Moorkkanad",
      "Nenmini",
      "Pathaikkara",
      "Perintalmanna",
      "Pulamanthole",
      "Puzhakkattiri",
      "Thazhekkode",
      "Vadakkangara",
      "Valambur",
      "Vettathoor"
    ],
    "Ponnani": [
      "Alamkode Malappuram",
      "Edappal",
      "Ezhavathuruhy",
      "Kalady Ponnani",
      "Marancheri",
      "Nannamukku",
      "Perumpadappu",
      "Ponnani Nagaram",
      "Thavanur",
      "Vattamkulam",
      "Veliyancode"
    ],
    "Tirur": [
      "Ananthavoor",
      "Athavanad",
      "Cheriyamundam",
      "Edayur",
      "Irimbiliyam",
      "Kalpakanchery",
      "Kattipparuthy",
      "Kottakkal",
      "Kurumbathoor",
      "Kuttippuram",
      "Mangalam",
      "Marakkara",
      "Melmmuri",
      "Naduvattom",
      "Niramaruthur",
      "Ozhur",
      "Pariyapuram",
      "Perummanna",
      "Ponmala",
      "Ponmundam",
      "Purathur",
      "Tanalur",
      "Tanur",
      "Thalakkad",
      "Thirunavaya",
      "Thrikkandiyoor",
      "Tirur",
      "Triprangode",
      "Valavannur",
      "Vettom"
    ],
    "Tirurangadi": [
      "A R Nagar",
      "Ariyallur",
      "Edarikkode",
      "Kanamangalam",
      "Moonniyur",
      "Nannambra",
      "Neduva",
      "Othukungal",
      "Parappanangadi",
      "Parappur",
      "Peruvallur",
      "Tenhippalam",
      "Thennala",
      "Tirurangadi",
      "Uurakam",
      "Vallikunnu",
      "Vengara"
    ]
  },
  "Kozhikode": {
    "Koyilandy": [
      "Arikkulam",
      "Atholi",
      "Avidanallur",
      "Balussery",
      "Chakkittappara",
      "Changaroth",
      "Chemancheri",
      "Chempanoda",
      "Chengottukavu",
      "Cheruvannur Koyilandi",
      "Eravattur",
      "Iringal",
      "Kayanna",
      "Keezhariyur",
      "Koorachundu",
      "Koothali",
      "Kottur",
      "Kozhukkallur",
      "Menhanyam",
      "Meppayyur",
      "Moodadi",
      "Naduvannur",
      "Nochad",
      "Paleri",
      "Panthalayani",
      "Payyoli",
      "Perumbra Koilandy",
      "Thikkodi",
      "Thurayur",
      "Ulliyeri",
      "Viyur"
    ],
    "Kozhikode": [
      "Beypore",
      "Chathamangalam",
      "Chelannur",
      "Chelavur",
      "Cheruvannoor",
      "Chevayur",
      "Elathur",
      "Feroke",
      "Kachery",
      "Kadalundy",
      "Kakkad",
      "Kakkodi",
      "Kakkur",
      "Karuvanthiruthi",
      "Kasaba",
      "Kodiyathur",
      "Kottooli",
      "Kumaranallur",
      "Kunnamangalam",
      "Kuruvattoor",
      "Kuttikkattoor",
      "Madavur",
      "Mavoor",
      "Nagaram",
      "Nanminda",
      "Neeleswaram",
      "Nellikode",
      "Olavanna",
      "Panniyankara",
      "Pantheerankavu",
      "Perumanna",
      "Peruvayal",
      "Poolakkode",
      "Puthiyangadi",
      "Ramanattukara",
      "Thalakkulathur",
      "Thazhekode",
      "Valayanad",
      "Vengeri"
    ],
    "Thamarassery": [
      "Eangapuzha",
      "Kanthalad",
      "Kattippara",
      "Kedavur Thamarassery",
      "Kinaloor",
      "Kizhakkoth",
      "Kodanchery",
      "Koduvally",
      "Koodaranhi",
      "Koodathai",
      "Narikkuni",
      "Nellipoyil",
      "Panangad",
      "Puthoor",
      "Puthuppady",
      "Raroth",
      "Sivapuram",
      "Thiruvampady",
      "Unnikulam",
      "Vavad"
    ],
    "Vatakara": [
      "Ayanchery",
      "Azhiyur",
      "Chekkiad",
      "Chorode",
      "Edacheri",
      "Eramala",
      "Kavilumpara",
      "Kayakkodi",
      "Kottappally",
      "Kunnummal",
      "Kuttiady",
      "Maniyur",
      "Maruthonkara",
      "Nadakkuthazha",
      "Nadapuram",
      "Narippatta",
      "Onchiyam",
      "Palayad",
      "Purameri",
      "Thinoor",
      "Thiruvalloor",
      "Tuneri",
      "Valayam",
      "Vanimel",
      "Vatakara",
      "Velom",
      "Vilangad",
      "Villiappally"
    ]
  },
  "Wayanad": {
    "Mananthavady": [
      "Anjukunnu",
      "Cherukattoor",
      "Edavaka",
      "Kanjirangad",
      "Mananthavady",
      "Nallurnad",
      "Panamaram",
      "Payyampally",
      "Peria",
      "Porunnanore",
      "Thavinhal",
      "Thirunelly",
      "Thondernad",
      "Thrissilery",
      "Valad",
      "Vellamunda"
    ],
    "Sulthan Bathery": [
      "Ambalavayal",
      "Cheeral",
      "Irulam",
      "Kidanganad",
      "Krishnagiri",
      "Kuppadi",
      "Nadavayal",
      "Nenmeni",
      "Noolpuzha",
      "Padichira",
      "Poothadi",
      "Pulpally",
      "Purakkadi",
      "Sulthan Bathery",
      "Thomattuchal"
    ],
    "Vythiri": [
      "Achooranam",
      "Chundale",
      "Kalpetta",
      "Kaniyambetta",
      "Kavumandam",
      "Kottappadi",
      "Kottathara",
      "Kunnathidavaka",
      "Kuppadithara",
      "Muppainad",
      "Muttil North",
      "Muttil South",
      "Padinjharathara",
      "Pozhuthana",
      "Thariode",
      "Thrikkaipetta",
      "Vellarimala",
      "Vengappally"
    ]
  },
  "Kannur": {
    "Iritty": [
      "Aralam",
      "Ayyankunnu",
      "Chavassery",
      "Kalliad",
      "Kanichar",
      "Keezhur",
      "Kelakam",
      "Kolari",
      "Kottiyoor",
      "Manathana",
      "Muzhakkunnu",
      "Nuchiad",
      "Padiyur Iritty",
      "Payam",
      "Pazhassi",
      "Thillenkeri",
      "Vayathur",
      "Vellarvalli",
      "Vilamana"
    ],
    "Kannur": [
      "Anjarakandy",
      "Azhikode North",
      "Azhikode South",
      "Chelora",
      "Chembilode",
      "Cherukunnu",
      "Chirakkal",
      "Edakkad",
      "Elayavoor",
      "Iriveri",
      "Kadambur",
      "Kalliasseri",
      "Kanhirode",
      "Kannadiparamba",
      "Kannapuram",
      "Makreri",
      "Mattool",
      "Mavilayi",
      "Munderi",
      "Muzhappilangad",
      "Narath",
      "Pallikkunnu",
      "Pappinisseri",
      "Puzhathi",
      "Valapattanam",
      "Valiyannur"
    ],
    "Payyannur": [
      "Alappadambu",
      "Cheruthazham",
      "Eramam",
      "Ezhom",
      "Kadannappally",
      "Kankol",
      "Karivellur",
      "Korom",
      "Kunjhimangalam",
      "Kuttur Payyannur",
      "Madayi",
      "Panappuzha",
      "Payyannur",
      "Peralam",
      "Peringom",
      "Perinthatta",
      "Pulingom",
      "Ramanthali",
      "Thirumeni",
      "Vayakkara",
      "Vellora",
      "Vellur"
    ],
    "Taliparamba": [
      "Alakode",
      "Anthoor",
      "Cheleri",
      "Chengalayi",
      "Chuzhali",
      "Eruvessy",
      "Irikkur",
      "Kayaralam",
      "Kolachery",
      "Koovery",
      "Kurumathur",
      "Kuttyattur",
      "Kuttyeri",
      "Malappattam",
      "Mayyil",
      "Morazha",
      "New Naduvil",
      "Nidiyenga",
      "Panniyoor",
      "Pariyaaram",
      "Pattuvam",
      "Payyavoor",
      "Sreekandapuram",
      "Taliparamba",
      "Thimiri",
      "Udayagiri",
      "Vellad"
    ],
    "Thalassery": [
      "Cheruvanchery",
      "Chokli",
      "Dharmadam",
      "Eranholi",
      "Eruvatty",
      "Kandamkunnu",
      "Kannavam",
      "Kathirur",
      "Keezhallur",
      "Kodiyeri",
      "Kolavallur",
      "Kolayad",
      "Koodali",
      "Kotayam",
      "Kuthuparamba",
      "Manantheri",
      "Mangattidam",
      "Mokeri",
      "Paduvilayi",
      "Panniyannore",
      "Panoor",
      "Pathiriyad",
      "Pattanur",
      "Pattiam",
      "Peringathur",
      "Pinarayi",
      "Puthur Kannur",
      "Shivapuram",
      "Tholambra",
      "Triprangottur",
      "Vekkalam"
    ]
  },
  "Kasaragod": {
    "Hosdurg": [
      "Ajanur",
      "Ambalathara",
      "Balla",
      "Bare",
      "Cheemeni",
      "Cheruvathur",
      "Chithari",
      "Hosdurg",
      "Kanhangad",
      "Kayyur",
      "Keekan",
      "Klayikode",
      "Kodakkad",
      "Kottikulam (pallikkara 2)",
      "Madikkai",
      "Maniyat",
      "Nileswaram",
      "North Trikkaripur",
      "Padne",
      "Pallikkara 1",
      "Panayal",
      "Periye",
      "Perole",
      "Pilicode",
      "Pullur",
      "Puthukkai",
      "South Trikkaripur",
      "Thimiri Kasargod",
      "Udinur",
      "Udma",
      "Valiyaparamba"
    ],
    "Kasaragod": [
      "Adhur",
      "Adkathbayal",
      "Adur",
      "Badiadukka",
      "Bandaduka",
      "Bedadukka",
      "Bela",
      "Bellur",
      "Chemnad",
      "Chengala",
      "Delampady",
      "Kalanad",
      "Karadka",
      "Karivedakam",
      "Kasaragod",
      "Kolathur",
      "Kudlu",
      "Kumbadaje",
      "Kuttikol",
      "Madhur",
      "Muliyar",
      "Munnad",
      "Muttathodi",
      "Neerchal",
      "Nekraje",
      "Nettanige",
      "Padi",
      "Patla",
      "Perumbala",
      "Puthur Kasargod",
      "Shiribagilu",
      "Thalangara",
      "Thekkil",
      "Ubrangala"
    ],
    "Manjeswaram": [
      "Angadimogaru",
      "Arikkady",
      "Badaje",
      "Badoor",
      "Bambrana",
      "Bangramanjeshwar",
      "Bayar",
      "Bekkur",
      "Chippar",
      "Edanad",
      "Enmakaje",
      "Herur",
      "Hosabettu",
      "Ichilampadi",
      "Ichilangod",
      "Kadambar",
      "Kaliyoor",
      "Kannur",
      "Kattukukke",
      "Kayyar",
      "Kidhur",
      "Kodibayal",
      "Kodlamogaru",
      "Koipady",
      "Koliyoor",
      "Kubannur",
      "Kudalmerkala",
      "Kuloor",
      "Kunjathur",
      "Majibayal",
      "Mangalpady",
      "Meenja",
      "Mogral",
      "Moodambayal",
      "Mugu",
      "Mulinja",
      "Padre",
      "Paivalike",
      "Pathur",
      "Pavoor",
      "Puthige",
      "Sheni",
      "Shiriya",
      "Thalakala",
      "Udyavar",
      "Ujarulwar",
      "Uppala",
      "Vorkady"
    ],
    "Vellarikkundu": [
      "Balal",
      "Belur",
      "Bheemanady",
      "Cheemeni Ii",
      "Chittarikkal",
      "Kallar",
      "Karinthalam",
      "Kinanoor",
      "Kodoth",
      "Maloth",
      "Palavayal",
      "Panathady",
      "Parappa",
      "Thayannur",
      "West Eleri"
    ]
  }
};

export function keralaTaluksForDistrict(district: string): string[] {
  return Object.keys(KERALA_VILLAGES[district] ?? {});
}

export function keralaVillagesForTaluk(district: string, taluk: string): string[] {
  return KERALA_VILLAGES[district]?.[taluk] ?? [];
}
