name = "netundo-speedtest"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[[routes]]
pattern = "speed.netundo.in/*"
zone_name = "netundo.in"
